### ISSUE TITLE
TPP-00118: Change nav bar colours when info and settings are selected

### ISSUE THREAD

**Issue by faye-tan** [uoftblueprint/the-period-purse#118]
> As a user I would like the colour scheme to be consistent

Current state of affairs: 
- default selection colours
<img width="323" alt="Screen Shot 2022-04-02 at 11 30 58 AM" src="https://user-images.githubusercontent.com/35851484/161390193-31244a81-4f02-4cb1-be4b-a12e0fd8bd2f.png">
<img width="299" alt="Screen Shot 2022-04-02 at 11 31 09 AM" src="https://user-images.githubusercontent.com/35851484/161390199-0a91cd14-6e06-45cb-837a-875e4fed710b.png">

What we would like: 
- When selected, Info icon and text should be this color -> #5A9F93 
- Same for Settings icon and text
<img width="217" alt="Screen Shot 2022-04-02 at 11 32 00 AM" src="https://user-images.githubusercontent.com/35851484/161390233-32eceda4-76e2-44ed-88bb-2109a15c6fde.png">
<img width="158" alt="Screen Shot 2022-04-02 at 11 32 51 AM" src="https://user-images.githubusercontent.com/35851484/161390260-ab2b5e63-33c6-4198-85d6-eb51e80970b9.png">

**Comment by faye-tan** [comment]
- unsaved modal when swipe down
- arrow when it disappears text is shifting in log symptoms when changing from today's date to yesterday's date
- blood icon disappears for log select symptoms option screen 
- middle button should be green calendar in cycle that leads back to the calendar tab. It should only be red plus on the calendar tab, and not in the cycle tab

**Comment by yuemily24** [comment]
- shrink padding top for header of `LogSymptomsScreen`
