### ISSUE TITLE
Website popups

### ISSUE THREAD

**Issue by pedropcamellon** [uoftblueprint/the-period-purse#169]
Hi! I think it would be better not showing these popups when exploring the website:

![image](https://user-images.githubusercontent.com/83567517/195986759-22ebe0c1-e5bf-4c12-b7d0-8048cf3d3dfc.png)

**Comment by yichenesia** [comment]
Hi there @pedropcamellon !

Thank you for bringing up this issue, however, this is the github repository for The Period Purse's **iOS** application. 

We are _**not maintainers**_ of The Period Purse's website, and thus, we do not have any say in their website design.

If you could email your concerns to [Hello@ThePeriodPurse.com](mailto:Hello@ThePeriodPurse.com), I'm sure they'd take your suggestion into mind!
