### ISSUE TITLE
TPP-00047: Fix colours on navbar

### ISSUE THREAD

**Issue by faye-tan** [uoftblueprint/the-period-purse#47]
> As a user, I want the nav bar to look ✨ aesthetic ✨ 

**Technical Information:**
- If I am on the info or settings tab, I want it to be highlighted appropriately 

**Styling Requirements:**
<img width="529" alt="Screen Shot 2021-12-27 at 1 33 46 PM" src="https://user-images.githubusercontent.com/35851484/147501861-fdd8e6bc-b6dd-467c-b79f-e98bf9f272b0.png">
- Both icon and text should be highlighted with teal

**Comment by yichenesia** [comment]
Completed in one of our many quick fix PRs
