### ISSUE TITLE
TPP-00091: Create the Cycle page and connect backend

### ISSUE THREAD

**Issue by yichenesia** [uoftblueprint/the-period-purse#91]
> As a user, I want to be able see information about my cycle with live data from my past period history.

## **Technical Information:**

- Create a top bar that will allow the user to navigate from the calendar -> cycle page and vice versa
- On the calendar page, when you tap the "Cycle" button on the top bar, you will be navigated to the Cycle page with the Period Cycle Donut, as well as average cycle calculations. 
![image](https://user-images.githubusercontent.com/59180843/154394826-8d9d4ea5-e494-4d0f-a436-ebcdac26bf3f.png)
  - Create the main page (with the cycle donut) and the sub page (the cycle history)
  - On the main cycle page, add:
    1. The cycle donut card with the cycle donut; try this package [circular progress indicator](https://www.npmjs.com/package/react-native-circular-progress-indicator). Link it up with `GETCycleDonutPercent`
    2. The two cards with average period length and cycle length and link it up by getting data through `GETAveragePeriodLength` and `GETAverageCycleLength`
    3. The cycle history card, linking to the cycle history page when tapping on "Show more". You do not need to display the data yet, so leave the card blank except for title & button linking it to the other page.
    4. Create a card for the "Your period might be coming within the next X days" that will be slotted on top of the cycle donut card. For now, keep it visible at all times.
    - Point of Discussion: Might need a backend method that grabs the next 'predicted' period start date?

- The cycle history page will be blank.

## **Styling Requirements:** 

[Figma V2](https://www.figma.com/file/SUHIyve6h6ruZNOste2oPN/TPP-design?node-id=48%3A23959)

For the cycle donut, try to get as close to the cycle donut in the Figma designs as possible. The most important part would be the number in the center (25 days since your period), and then the colors.

For every other card listed above, try to get the CSS styling as close to the colors, font size, positioning and etc as possible.

![image](https://user-images.githubusercontent.com/59180843/154396202-a976217b-757a-4fae-b462-4ed50d145c73.png)

![image](https://user-images.githubusercontent.com/59180843/154395891-7e250898-0306-45fa-9314-fbf5606d1667.png)

![image](https://user-images.githubusercontent.com/59180843/154822031-e4ab0949-c6a8-4a94-ad88-b7204f4ecfbb.png)

**Comment by kenneth-miura** [comment]
Cycle: https://github.com/RobertFOConnor/react-native-progress-wheel
Tabs: https://reactnavigation.org/docs/material-top-tab-navigator/
